let niceAdj = "able clean enthusiastic heartening meek reasonable talented accommodating clever ethical helpful meritorious refined temperate accomplished commendable excellent statuesque high-class moral reliable terrific adept compassionate exceptional honest neat remarkable tidy admirable composed exemplary honorable noble resilient top quality agreeable considerate exquisite hopeful obliging respectable tremendous amazing consummate extraordinary humble observant respectful trustworthy appealing cooperative fabulous important optimistic resplendent trusty astute correct faithful impressive organized responsible truthful attractive courageous fantastic incisive outstanding robust unbeatable awesome courteous fascinating incredible peaceful selfless understanding beautiful dazzling fine innocent perceptive sensational unequaled benevolent decent first-class insightful perfect sensible unparalleled brave delightful fortitudinous inspiring pleasant serene upbeat breathtaking dependable gallant intelligent pleasing sharp valiant bright devoted generous joyful polite shining valuable brilliant diplomatic gentle judicious positive shrewd vigilant bubbly discerning gifted just praiseworthy smart vigorous buoyant disciplined giving kindly precious sparkling virtuous calm elegant gleaming laudable priceless spectacular well mannered capable elevating glowing likable principled splendid wholesome charitable enchanting good lovable prompt steadfast wise charming encouraging gorgeous lovely prudent stunning witty chaste endearing graceful loyal punctual super wonderful cheerful energetic gracious luminous pure superb worthy chivalrous engaging great magnanimous quick superior zesty gallant enhanced happy magnificent radiant supportive civil enjoyable hardy marvelous rational supreme".split(' '); 
let meanAdj = "aggressive aloof arrogant belligerent big-headed bitchy boastful bone-idle boring bossy callous cantankerous careless changeable clinging compulsive conservative cowardly cruel cunning cynical deceitful detached dishonest dogmatic domineering finicky flirtatious foolish foolhardy fussy greedy grumpy gullible harsh impatient impolite impulsive inconsiderate inconsistent indecisive indiscreet inflexible interfering intolerant irresponsible jealous lazy Machiavellian materialistic mean miserly moody narrow-minded nasty naughty nervous obsessive obstinate overcritical overemotional parsimonious patronizing perverse pessimistic pompous possessive pusillanimous quarrelsome quick-tempered resentful rude ruthless sarcastic secretive selfish self-centred self-indulgent silly sneaky stingy stubborn stupid superficial tactless timid touchy thoughtless truculent unkind unpredictable unreliable untidy untrustworthy vague vain vengeful vulgar weak-willed".split(" ");

let niceNouns = "Fellow Gentleperson Professional Master Impresario Pro GamerGirl Ownmaster Friend Lover BFF Companion Wunderkind Expert Comrade Alpha Free-Thinker Spirit Partner Sex-Haver Friendo Leader Adonis Aphrodite God Deity Prodigy".split(" ");
let meanNouns = "Alcoholic Amateur Analphabet Anarchist Ape Arse Arselicker Ass Ass-master Ass-kisser Ass-nugget Ass-wipe Asshole Baby Backwoodsman Balls Bandit Barbar Bastard Bastard Beavis Beginner Biest Bitch Blubber-gut Bogeyman Booby Boozer Bozo Brain-fart Brainless Brainy Brontosaurus Brownie Bugger Bulloks Bum Bum-fucker Butt Buttfucker Butthead Camel Cannibal Caveman Chaavanist Chaot Chauvi Cheater Chicken Clit Clown Cock Cockmaster Cockup Cockboy Cockfucker Cockroach Coky Con-man bumpkin Cow Creep Creep Cretin Criminal Daywalker Deathlord Dumb-brain Desperado Devil Dickhead Dinosaur Doodoohead Dog Dog, dirty Dogshit Donkey Drakula Dreamer Drinker Drunkard Dufus Dulles Dumbo Dummy Dumpy Egoist Eunuch Exhibitionist Fake Fanny Farmer Fart Fatso Fellow Fibber Fish Fixer Flake Flash-Harry Freak Frog Fuck Fuckface Fuckhead Fucknoggin Fucker Gangster Ghost Goose Gorilla Grouch Grump Fathead Helldog Hillbilly Hippie Hooligan Horsefucker Idiot Ignoramus Mutant Neanderthal Nerfherder Nobody Nerd Piggy-wiggy Pirate Pornofreak Prick Prolet Rat Rat-fink Reject Riff-Raff Ripper Roboter Rowdy Ruffian Sack Sadist Saprophyt Satan Scarab Schfincter Shark Shiteater Shithead Simulant Skunk Skuzbag Slave Sleeze Sleezebag Slimer Snail Snake Snob Snot Sonofabitch Square Stinker Stripper Stunk Swindler Swine Teletubby Weirdo Wino Witch Xenophobe Yak".split(" ");

let part1 = ["In my humble opinion ", "i guess in the end, ", "last night proved that ", "SUP TWITTER ", "gotta say it... ", "PSA: ", "the verdict is in- ", "i've been doing a lot of thinking in my life, and ", "callout time: ", "hot take: ", "few things are certain in this chaotic life, but one of them is that ", "welp i'ma just say it. ", "sup fools. ", "lol ", "ok so ", "funny story, i farted today. anyway ", "shoutout to someone special. ", "life is hellish and overall not worth it. also ", "haha twitter is dumb but "]
let part2 = ["is the prototypical ", "is a prime example of a ", "has spent a lifetime perfecting the art of being a ", "is undeniably a ", "could be described as a ", "? absolute ", "is a verified ", "is nothing less than a ", "can't help but be a ", "ain't nothin but a ", "is a ", ", you're a ", "seems like a ", "can only be summarized thusly: ", "if i had to sum it up, is, well... a ", "was born and will die a ", "posts like a ", "is universally known to be a "]
let part3 = ["just keepin it real.", "lol", "phew, load off my chest.", "lol jk", "anyway bye", ";)", ":j", "don't @ me", "luv ya kid", "holla"]


module.exports = {
  intro: part1,
  connector: part2,
  outro: part3,
  nice_adj: niceAdj,
  mean_adj: meanAdj,
  nice_noun: niceNouns,
  mean_noun: meanNouns
};